name: Go

on:
  workflow_dispatch:
    inputs:
      goVersion:
        description: "set go version"
        required: true
        default: '1.18'
        type: choice
        options:
        - "1.18"
        - "1.19"
        - "1.17"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.goVersion }}

    - name: Build
      run: go build main.go
