name: GO dispach event

on:
  workflow_dispatch:
    inputs:
      goVersion:
        description: "set go version"
        required: true
        default: '1.18'
        type: choice
        options:
        - "1.18"
        - "1.19"
        - "1.17"
      os:
        description: "set os system"
        required: true
        default: "ubuntu-latest"
        type: choice
        options:
          - "windows-latest"
          - "macos-latest"
          - "ubuntu-latest"

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.goVersion }}

    - name: Build
      run: go build main.go
