name: Docker Pull

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Pull & Run
      run: |
        docker pull alexmkoyan/go
        docker run alexmkoyan/go
