name: Docker Image Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nhakobyan685/hellogo:latest
    - name: Push image in Dockerhub
      run: |
        docker login -u nhakobyan685 -p ${{ secrets.DOCKER_TOKEN }}
        docker image push nhakobyan685/hellogo:latest
