# name: Docker Image Push

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag nhakobyan685/hellogo:latest
#     - name: Push image in Dockerhub
#       run: |
#         docker login -u nhakobyan685 -p ${{ secrets.DOCKER_TOKEN }}
#         docker image push nhakobyan685/hellogo:latest
# -----------------------
name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          username: nhakobyan685
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: nhakobyan685
          tags  :  goapp:latest


